version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.30
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
